export default {
  common: {
    noProductList: '非常抱歉，找不到和您查询相关的内容或信息',
    commonProducts: '常用产品',
    aliyunAPIDoc: '阿里云 API 文档',
    searchAPIDoc: '搜索 API 文档',
    hotDoc: '热门文档',
    aliyunRam: 'RAM 授权信息',
    searchRamDoc: '搜索云产品',
    search: '搜索',
    SDKCenter: 'SDK 中心',
    searchSDK: '搜索 SDK',
    hotSDK: '热门 SDK',
    aliyunOpenAPI: '阿里云 OpenAPI',
    searchOpenAPI: '搜索 OpenAPI',
    hotOpenAPI: '热门 OpenAPI',
    recentVisit: '最近访问',
    OpenAPIOverview: 'OpenAPI 概览',
    dara: '升级版',
    oldVersion: '原版',
    updateAt: '更新于',
    all: '全部',
    allProducts: '全部产品',
    noSDK: '暂无SDK',
    aliyunSDK: '阿里云 SDK',
    selectSDKVersion: 'SDK 版本选择：',
    see: '查看',
    difference: '区别',
    selectLang: '选择语言：',
    concise: '简洁',
    detail: '详细',
    goodText: 'API 质量不错，给工程师点个赞鼓励一下吧',
    badText: 'API 体验糟糕，反馈给云产品工程师改进吧',
    feedbackSuccess: '反馈成功！',
    giveGood: '点赞',
    debunkFeedback: '吐槽反馈',
    close: '关闭',
    submitSuccess: '提交成功!',
    submit: '提交',
    debunk: '吐槽',
    missOpenAPIFeedback: '缺 OpenAPI 反馈',
    describeYouNeedOpenAPI:
      '请描述您所需要的 OpenAPI，我们将参照您的描述为您提供',
    missAPI: '找不到 API ? 点击',
    toFeedback: '反馈吧',
    missDemoFeedback: '缺示例反馈',
    describeDemo: '请描述您需要的示例场景，我们将参照您的描述提供示例。',
    needDemo: '需要示例',
    hasFeedback: '(已反馈)',
    please: '请先',
    login: '登录',
    SDKMissLangFeedback: 'SDK 缺少语言反馈',
    inputYouNeedLang: '反馈您所需要的 SDK 语言',
    missLang: '没有我想要的语言, 点击',
    missErrorCodeFeedback: '缺少错误码反馈',
    inputYouNeedErrorCode:
      '请填写您需要的错误码，我们将参照您的描述提供错误码信息。',
    missErrorCode: '没有我想要的错误码, 点击',
    feedback: '反馈',
    APIParamsBadText: 'API 参数有问题，反馈给云产品工程师改进吧',
    version: '版本',
  },
  docIframe: {
    notOpen: '该云产品暂未开通 API 调试支持',
    define: '确定',
    apiCall: 'API调用 -',
    serviceAddress: '服务地址：',
    goodText: 'API 质量不错，给工程师点个赞鼓励一下吧',
    badText: 'API 体验糟糕，反馈给云产品工程师改进吧',
    recommend: '推荐',
    goDebug: '去 API 开发者门户中调试 >',
    SDKDemo: 'SDK 示例',
    debugResult: '调用结果',
    relatedDemo: '相关示例',
    errorCode: '错误码',
    overallErrorCode: '所有错误码',
  },
  explorer: {
    specialresponsetip:"暂不支持特殊返回结果查看",
    APIAbsent: '此API不存在',
    SDKReport: 'SDK 发布报告',
    commaWithSpace: '，',
    checkSDKReport: '查看 SDK 发布报告',
    emptystring: '空字符串',
    inputEmptyString: '输入空字符串',
    clearEmptyString: '清除空字符串',
    parameterDesc: '参数描述：',
    accountBanTip:
      '该接口不能使用阿里云账号（主账号）调用，只能使用 RAM 用户或 RAM 角色调用。',
    open: '开启',
    close: '关闭',
    parameterType: '参数类型',
    inputString: '请输入字符串',
    inputSth: '请输入{val1}',
    inputNumber: '请输入数字',
    delete: '删除',
    inputUrl: '输入URL',
    uploadFile: '上传文件',
    paramAnyTip: '该参数值为 any 类型，调试时请先选择参数类型，再输入参数值。',
    requestParameter: '请求参数',
    paramsExplain: '请求参数说明',
    quotaInfo: '流控信息',
    noQuotaInfo1: '当前云产品暂无流控信息透出，可通过',
    noQuotaInfo2: '向产品方了解',
    responseParameter: '响应参数',
    responseParamsExplain: '响应参数说明',
    noRelatedDemo: '暂无相关示例',
    moreQuotaInfo: '更多流控信息请前往',
    in: '在 ',
    region: 'region下，',
    quotaIconTips: '云产品的配额速率是指调用该云产品下所有API共享的流控阈值',
    quotaLoginTips:
      '当前展示的是云产品的默认配置，不同用户可能会有不同的流控配置，如需查看，请先',
    loginInfo: ' 您的',
    noLoginInfo: ' 当前',
    limitInfo: 'API配额速率为：',
    productLimitInfo: '， 当前云产品的配额速率为：',
    quotaCenter: '配额中心',
    gongdan: '工单',
    contributionDemo: '贡献示例',
    seeResults: '查看结果',
    AKTip:
      '已通过您的配置信息获取 Access Keys、发起调用可能对当前账号发起线上资源操作，请小心操作',
    APICallResult: 'API 调用结果',
    overview: '概览',
    success: '调用成功',
    fail: '失败',
    success1: '成功',
    error: '调用失败',
    noCall: '未调用',
    statusCode: '状态码:',
    time: '耗时:',
    previous: '上一页',
    next: '下一页',
    requestMethod: '请求方式：',
    onlineTryIssues: '在线试用有问题， 点击',
    onlineTryFeedback: '在线试用有问题，反馈给云产品工程师改进吧',
    feedback: '反馈',
    callFailCheck: '本次 OpenAPI 调用失败，点击查看',
    troubleshootResult: '本次诊断结果',
    orCheck: '或查看',
    callHasIssues: '对本次 OpenAPI 调用结果有疑问？点击',
    checkCallTroubleshoot: '查看 OpenAPI 使用诊断',
    noResult: '暂无调用结果',
    startCall: '发起调用',
    startCallResult: '发起调用后，您可以在此获取调用结果',
    fillParameters: '一键填入',
    noIntelligentParams: '当前API无推荐参数',
    intelligentSample: '参数组合推荐',
    noPopSave: '不再弹出',
    intelligentDebug: '参数推荐',
    intelligentGroupDebug: '参数组合推荐',
    loginToShowMoreSample: '登录查看更多参数推荐',
    intelligentSampleInfo:
      '参数组合是基于API历史调用信息推断出的参数模板，您可以通过点击「参数聚焦」来关注指定组合中的参数进行配置。',
    intelligentParamscombination: '推荐参数组合',
    parameterValue: '参数值',
    parameterValueInfo: '参数值推荐来源于历史调用，可能会存在失效的问题。',
    helpIntelligentSampleInfo: '点击查看什么是参数推荐',
    intelligentRateInfo: '该参数组合在所有成功调用中的占比。',
    successfulRate: '占比',
    SDKPackageName: 'SDK包名称',
    SDKVersion: 'SDK版本',
    SDKPackageVersion: 'SDK包版本',
    SDKPackageManage: 'SDK包管理平台',
    relatedLinks: '相关链接',
    SDKInstallCommand: 'SDK安装命令',
    SDKInfo: 'SDK信息',
    SDKDoc1: 'SDK文档',
    versionNotExist:
      "{val1}仓库可能会有延迟，如果遇到版本不存在的情况，请稍后再试{val2}` : ''\n          }",
    SDKVersionNotExist:
      "{val1}仓库可能会有延迟，如果遇到版本不存在的情况，请稍后再试{val2}` : ''\n          }",
    tip: '提示',
    codeGenerateError: '代码生成报错',
    SDKVersionOverdue: 'SDK 版本过期',
    SDKVersionOverdueTitle:
      '该 SDK 版本已过期，SDK 中尚未包含该 API 方法，请添加钉钉群（{val1}）反馈我们发布。',
    needLogin: '需要登录',
    placeLogin: '请登录您的阿里云账号',
    toLogin: '去登录',
    runExample: '沙箱运行',
    codeGenerating: '工程代码生成中...',
    generateCodeError: '工程代码生成失败，请在钉钉客服群中反馈。',
    downloadEngineering: '下载完整工程',
    copySuccess: '复制成功',
    copy: '复制',
    SDKDependentMessage: 'SDK 依赖信息',
    getAK: '获取 AK',
    unSupportDaraSDK: '该 OpenAPI 暂不支持新版 SDK',
    see: '查看',
    difference: '区别',
    akTip: '平台通过已登录用户信息获取当前账号临时 Access Keys、',
    runSDKDemo: '"运行 SDK 示例"',
    operationWarn: '可能对当前账号发起线上资源操作，请小心操作',
    SDKVersionSelect: 'SDK 版本选择',
    SDKHasIssue: 'SDK 有问题， 点击',
    badText: 'SDK 有问题，反馈给云产品工程师改进吧',
    switchOpen: '启用',
    useCommon: 'Common模式生成示例',
    useSDKFail: 'SDK示例生成失败，已为您跳转到Common模式生成示例',
    tryLater:
      "{val1}仓库可能会有延迟，如果遇到版本不存在的情况，请稍后再试{val2}` : ''\n          }",
    notOpen: '该云产品暂未开通 API 调试支持',
    define: '确定',
    goodText: 'API 质量不错，给工程师点个赞鼓励一下吧',
    badWord: 'API 体验糟糕，反馈给云产品工程师改进吧',
    serviceAddress: '服务地址：',
    attentionMatter: '注意事项',
    apiQuickTestGuide: ' API 快速测试指引（新用户免费测试指引）',
    paramsConfig: '参数配置',
    apiParamsConfig: 'API参数配置',
    runtimeOptions: '高级配置',
    credentialConfig: '鉴权方式配置',
    SDKDemo: 'SDK示例',
    CLIDemo: 'CLI示例',
    CLINotice:
      '使用之前，确保您已经开通了要使用的云产品并已了解该产品API的使用。',
    CLIIntroduce:
      '阿里云命令行工具（Alibaba Cloud Command Line Interface）是在Alibaba Cloud SDK for Go之上构建的开源工具。阿里云CLI提供了对阿里云云产品OpenAPI的直接访问。您可以在命令行Shell中，使用aliyun命令与阿里云服务进行交互，管理您的阿里云资源。',
    CLIUse: '具体使用方法，请查看',
    CLIUseGuide: '阿里云CLI使用指南',
    CLIProductIntroduce: '产品简介',
    CLIInstallGuide: '安装指南',
    CLICofig: '配置阿里云CLI',
    CLIUse1: '使用阿里云CLI',
    CLIExperience: '最佳实践',
    debugResult: '调用结果',
    OpenAPIDoc: 'OpenAPI 文档',
    relatedDemo: '相关示例',
    httpCode: 'Http 状态码',
    errorCode: '错误码',
    overallErrorCode: '所有错误码',
    globalErrorCode: '全局错误码',
    overallCodeSamples: '所有示例',
    floatNumber: '浮点数值',
    numver: '数值',
    number: '数值',
    string: '字符串',
    intNumber: '整型数字',
    add: '添加',
    shouldJSON: '{val1} 须为 JSON 格式',
    uploadFieldLimit: '暂不支持上传超过50M的文件哦!',
    clickUpload: '点击上传',
    reUpload: '重新上传',
    toBeAddParams: '待补充的参数:',
    noRequiredParameter: '调用该 OpenAPI 无需参数',
    withoutRequiredParams: '该 OpenAPI 无必填参数',
    empty: '清空',
    enums: '枚举值',
    showAll: '展示所有',
    seeRequired: '只看必填',
    callHistory: '调用历史',
    createdAt: '请求时间',
    callParams: '调用参数',
    checkCallParams: '查看调用参数',
    callStatus: '调用状态',
    operation: '操作',
    description: '描述',
    index: '编号',
    onlyParamsSample: '参数聚焦',
    API: 'API',
    APIVersionSelect: 'API版本：',
    debug: '调试',
    reDebug: '重新调试',
    APIDefaultPage: 'API 默认页',
    openAPIName: 'OpenAPI 名称',
    describe: '描述',
    seeDoc: '查看文档',
    seeAPIDoc: '查看文档',
    goDebug: '去调试',
    goCall: '去调用',
    OpenAPIOverview: '{val1} - OpenAPI 概览',
    OpenAPIImperfectWarn:
      '{val1} 版本的 OpenAPI 尚不完善, 不推荐使用，建议使用其他推荐的 API 版本',
    notRecommendedVersion: '不推荐该版本',
    OpenAPIVersion: 'OpenAPI 版本：',
    closeOverviewPage: '关闭概览页面',
    OpenAPIWarn:
      '{val1} 版本的 OpenAPI 尚不完善, 不推荐使用，建议使用其他推荐 API 版本',
    notRecommended: '不推荐',
    getSDK: '获取 SDK',
    getMeta: '获取元数据',
    regionList: '服务地域列表',
    title: '名称',
    regionId: '区域 ID',
    endPoint: '服务地址',
    copySucc: '复制成功!',
    serviceAdd: '服务地域',
    pleaseSearchAPI: '请搜索 API，支持中英文搜索',
    openAPIOverview: 'OpenAPI 概览',
    allLanguages: '所有语言',
    noDemo: '暂无示例',
    recommend: '推荐',
    noDaraSDK: '暂无V2.0 SDK',
    daraSDK: 'V2.0 SDK',
    noOldSDK: '暂无V1.0 SDK',
    oldSDK: 'V1.0',
    recentSearch: '最近搜索',
    hotSearch: '最热搜索',
    docOverview: '文档概览',
    demoCenter: '示例中心',
    product: '云产品',
    openAPIVersion: 'OpenAPI 版本',
    SDKMessage: 'SDK 信息',
    SDKDoc: 'SDK 文档',
    daraModule: 'Darabonba 模块',
    demoNice: '示例很棒',
    demoBad: '示例有问题，我要吐槽',
    demoIntro: '示例简介：',
    noIntro: '暂无简介',
    contributor: '贡献者：',
    codeBrowser: '代码浏览',
    relatedOpenAPI: '示例中相关 OpenAPI',
    demoDes:
      '请描述您需要的示例场景，或者提供示例涉及的API名称（例：DescribeUserStatus），我们将参照您的描述提供示例。',
    loading: '加载中',
    noParams: '暂无参数',
    paramsBad: '请求参数有问题，反馈给云产品工程师改进吧',
    type: '类型',
    requestTime: '调用时间',
    required: '必填',
    yes: '是',
    no: '否',
    sampleValue: '示例值',
    badParams: '响应参数有问题，反馈给云产品工程师改进吧',
    demo: '示例',
    APIVersion: 'API 版本',
    createdTime: '创建时间',
    updatedAt: '更新时间',
    badErrorCode: '错误码有问题，反馈给云产品工程师改进吧',
    errorMessage: '错误信息',
    troubleshoot: '诊断',
    goodDoc: '这篇文档不错，点个赞',
    badDoc: '这篇文档有问题，我要吐槽',
    APIDes: '接口说明',
    requestDes: '请求说明',
    returnValue: '返回数据',
    returnDes: '返回说明',
    returnDemo: '返回示例',
    rightReturnDemo: '正常返回示例',
    format: '格式',
    errorReturnDemo: '错误返回示例',
    docCenter: '文档中心',
    notRecommendAPI:
      '{val1} 版本的 OpenAPI 尚不完善, 不推荐使用，建议使用其他推荐 API 版本',
    searchAPI: '输入 API 进行搜索',
    demoTip:
      '文档中示例代码是以产品 ECS 举例子来展示阿里云产品的使用步骤，真正的该产品 SDK 的使用步骤可以参考：',
    noData: '暂无数据',
    SDKCenter: 'SDK 中心',
    goodSDK: 'SDK 不错，点个赞',
    badSDK: 'SDK 有问题，我要吐槽',
    apiVer: 'API 版本 :',
    noDoc: '暂无文档',
    sdkRelatedDemo: 'SDK 相关示例',
    legalStatement: '法律申明及隐私权政策',
    reportAgainseCorruption: '廉正举报',
    comma: '，',
    fullStop: '。',
    colon: '：',
    EnumEmptyString: '如果QueryProductList返回ProductType=""，请输入空格',
    parenthesesLeft: '（',
    laterTryAgain: '仓库可能会有延迟，如果遇到版本不存在的情况，请稍后再试',
    tryOldVersionLater: '，或者使用旧版本{val1}',
    changeHistory: '变更历史',
    isRequied: '{val1} 是必填参数',
    syncDelay:
      '仓库同步可能会有延迟，如果遇到版本不存在的情况，请稍后再试或使用上一个版本。',
    changeInput: '转换为 Input，转换后将丢失换行符',
    withoutChangeRecord: '暂无变更记录',
    changeHistoryC: '{val1} - 变更历史',
    changeItem: '变更项',
    changeContent: '变更内容',
    messageChangeTo: '描述信息变更为：{val1}',
    pleaseOpenDetail: ', 请展开查看变更细节',
    detail: '{val1}{val2}变更',
    addRecord: '新增{val1}: {val2}',
    deleteRecord: '删除{val1}: {val2}',
    changeContentSummary: '变更内容概要',
    changeDetail: 'OpenAPI {val1} 变更详情',
    checkChangeDetail: '查看变更详情',
    checkChangeHistory: '查看API变更历史',
    checkAPIDoc: '查看API文档',
    changeDate: '变更时间：{val1}',
    changeDes: '变更集发布说明：{val1}',
    changeTime: '变更时间',
    openAPIChangeDetail: 'OpenAPI {val1} 变更详情',
    checkChanges: '查看变更集',
    withoutChangeHistory: '暂无变更历史',
    openAPISummary: '{val1} - OpenAPI 概览',
    notRecommendedVersionAPI:
      '{val1} 版本的 OpenAPI 尚不完善, 不推荐使用，建议使用其他推荐的 API 版本',
    notRecommendedVeersionAPIC:
      '{val1} 版本的 OpenAPI 尚不完善, 不推荐使用，建议使用其他推荐 API 版本',
    nonExistAPI: '该API不存在,请选择其他API.',
    notRecommendedVersionAPIA:
      '{val1} 版本的 OpenAPI 尚不完善, 不推荐使用，建议使用其他推荐 API 版本',
    productNoSDK: '由于ECI产品暂时不支持自动生成SDK样例，仅支持参数调试功能。',
    sdkReference: 'ECI SDK 使用请参考: ',
    goEdit: '去编辑',
    tryByteNum: '总计 {val1} 个字节',
    byteParse: '辅助解析',
    gaiZhi: '该值',
    apiChangeSubscribe: '订阅变更',
    signName: '短信签名',
    templateCode: '短信模版',
    messageSignNameAuditNotPass: '短信签名 {val1} 未审核通过',
    messageSignNameAuditNotApply: '短信签名 {val1} 未申请',
    messageTemplateAuditNotPass: '短信模版 {val1} 未审核通过',
    messageTemplateAuditNotApply: '短信模版 {val1} 未申请',
    messageTemplateParamError: '测试专用模版中的变量只支持4-6位纯数字',
    messageSmsTestError: '测试专用签名和模版必须结合使用',
    messageJsonError: '参数格式错误，格式示例：{"code":"1234"}',
    addSth: '创建{val1}。',
    alsoUseAPI: '或调用 API ',
    addSignNameInfo: '，在签名管理页面获取，',
    addTemplateInfo: '，在模板管理页面添加模板CODE，',
    auditPass: '审核通过',
    auditInit: '审核中',
    auditNotPass: '审核未通过',
    auditCancel: '已取消审核',
    canLogin: '您可以登录',
    smsPlatform: '短信服务控制台',
    applyIsEmpty: '没有可用的{val1}。',
    updateTime: '更新时间: {val1}',
    offline: '下线',
    deprecated: '该API被标记为deprecated，不建议被继续使用',
    recommendAPI: '目前API接口已弃用，推荐替代API',
  },
  home: {
    aboutUs: '关于我们',
    contactUs: '联系我们',
    reportAgainstCorruption: '廉正举报',
    legalStatement: '法律申明及隐私权政策',
    joinAliyun: '加入阿里云',
    alibabaGroup: '阿里巴巴集团',
    taobao: '淘宝网',
    tianmao: '天猫',
    juhuasuan: '聚划算',
    sumaitong: '全球速卖通',
    internationalTransactions: '阿里巴巴国际交易市场',
    alimama: '阿里妈妈',
    feizhu: '飞猪',
    aliyun: '阿里云计算',
    tongxin: '阿里通信',
    wanwang: '万网',
    gaode: '高德',
    youmeng: '友盟',
    xiami: '虾米',
    youku: '优酷',
    dingding: '钉钉',
    zhifubao: '支付宝',
    damo: '达摩院',
    anquan: '阿里安全',
    licence: 'Aliyun.com 版权所有 增值电信业务经营许可证：',
    zhe: '浙B2-20080101',
    keepOnRecord: '浙公网安备 33010602009975号',
    hotDemo: '热门示例',
    seeAll: '查看全部',
    demo: '示例',
    openAPIDoc: 'OpenAPI 文档',
    document: '文档',
    quotaInfo: '流控',
    openAPIOverview: 'OpenAPI 概览',
    dataIsEmpty: '数据为空',
    toContribute: '前去贡献',
    please: '请先',
    login: '登录',
    hot: '热门',
    recentVisit: '最近访问',
    myContribution: '我贡献的',
    showMore: '展开更多',
    javaOnline: '【Java开发】在线调试和生成SDK示例',
    quickEnter: '快速入门',
    main: '首推',
    other: '其他',
    seeMore: '查看更多',
    useProcess: '使用流程',
    tryAPI: '试用及调试 OpenAPI ',
    troubleShoot: '诊断试用',
    statistics: '调用统计',
    openAPIDebug: 'OpenAPI 调试',
    shoot: '诊断',
    troubleshootTip:
      '粘贴完整的 RequestID、SDK报错信息或鹰眼 ID，快速帮您定位问题，找到解决方案',
    errorCode: '错误中心',
    callTrend: '调用趋势',
    onlineSoon: '即将上线，敬请期待',
    errorCodeDistribution: '错误分布',
    callTrendSubTitle: '洞悉您在阿里云的OpenAPI调用情况',
    errorCodeSubTitle:
      '监控您在阿里云的OpenAPI调用稳定性，洞察您的API调用出错原因。',
    enterErrorMessage: '输入报错信息…',
  },
  notFound: {
    pageLoss: '页面丢失了...',
    pageMiss: '页面丢失了...',
    returnHome: '回到首页',
    seeEverything: '调用数据一览无余',
    seeCallSituation: '了解您使用的云产品OpenAPI调用情况',
    seeErrorCodeDistribution: '了解您使用OpenAPI时出现的错误及错误码分布',
    openAPIPortal: 'OpenAPI 开发者门户',
    pleaseBegin: '从这里开始，集成阿里云 OpenAPI',
    debug: '试用及调试',
    APIDoc: 'API 文档',
    APIDebug: 'API 调试',
  },
  portal: {
    shootCenter: '诊断中心',
    hotPractice: '热门实践',
    fullCoverage: '全覆盖常用六门语言 SDK 的场景化示例',
    seeAll: '查看全部 >',
    noContributionRecord: '暂无贡献记录',
    database: '云服务器 ECS',
    vpc: '专有网络',
    ram: '访问控制',
    slb: '负载均衡',
    alidns: '云解析',
    rds: '云数据库 RDS',
    billing: '阿里云 Billing',
    ddos: '新BGP高防IP',
    cs: '容器服务Kubernetes版',
    cdn: '内容分发',
    dds: '云数据库 MongoDB',
    portalSubtitle:
      '本门户一站式提供 OpenAPI 的文档、调试工具、SDK 及示例，帮助您快速入门 API 开发',
    hotProduct: '热门产品',
    recentDebug: '最近调用',
    noRecentAPI: '暂无最近调用 API',
    noRecentVisit: '暂无最近访问记录',
    APIDebug: 'API 调用',
    troubleshootSubtitle: '帮助开发者更高效地诊断 OpenAPI 使用过程中的问题',
    shootIssues: '问题诊断',
    troubleshootPlaceholder:
      '910F1381-9999-7777-8888-AAAAAA4B2952 （RequestID，推荐）                                                       \nInvalidEngine.NotSupported  （错误码）\nthe endTime - startTime should be less than 31 days（错误消息）',
    confirm: '确认',
    errorCodeCenterSubtitle: '输入错误码，快速帮您定位问题，找到解决方案',
    pleaseInputErrorCode: '请输入错误代码',
  },
  product: {
    npsRecommendValue: 'NPS 净推荐值：',
    scoreSuccess: '打分成功。',
    scoreWarn: '30天内只允许打分一次，请您在 {val1} 天后更新打分~',
    npsContent: '您在多大程度上愿意将',
    recommendTitle: '的 OpenAPI 推荐给你的朋友？',
    dissatisfied: '非常不愿意',
    satisfied: '非常愿意',
    APIOverview: 'API 概览',
    APIVersion: 'API 版本：',
    notRecommendVersion:
      '{val1} 版本的 OpenAPI 尚不完善, 不推荐使用，建议使用其他推荐 API 版本',
    endpoints: '服务区域列表',
    recommentVersion: '推荐 API 版本 :',
    apiNumber: '默认版本 API 数量 :',
    regionNumber: '服务区域数 :',
    demoNumber: 'SDK 示例数 :',
    isSupportDaraSDK: '是否支持V2.0 SDK :',
    oldSDKLang: 'V1.0 SDK 支持语言 :',
    notSupport: '不支持',
    allCallNumver: '总调用次数',
    allCallNumber: '总调用次数',
    errorTrend: '错误趋势',
    clickSee: '点击访问',
    apiChangeHistory: 'API 变更历史 :',
  },
  statistics: {
    callErrorNumber: '调用出错次数',
    noCallData: '暂无调用数据',
    productName: '产品名',
    callErrorPercent: '调用出错率',
    seeDetail: '查看调用出错详情',
    noCallError: '无调用出错',
    callSuccessNumber: '调用成功次数',
    productCallNumber: '云产品调用次数',
    bar: '条形图',
    pie: '饼图',
    table: '表格',
    noCallDataDay: '该日暂无调用数据',
    versionCallNumber: 'API 版本调用次数',
    noCallDataProduct: '该产品暂无调用数据',
    APIName: 'API 名称',
    APICallNumber: 'OpenAPI 调用次数',
    noCallDataVersion: '该版本暂无调用数据',
    chartsDataWarn:
      '本页面展示数据为，您在阿里云的 OpenAPI 调用数据。本页面数据为离线数据（T - 1），当前仅支持一个月前至昨日（T - 30 ~ T - 1）的时间筛选。欢迎添加钉钉群：31698589，对本功能提出您宝贵的建议',
    number: '数量',
    percent: '占比',
    errorCodeDistribution: '错误码分布',
    noCallErrorCode: '暂无调用错误码',
    errorCodeNumber: '错误次数',
    productErrorCodeDistribution: '云产品错误分布',
    thisDayNoData: '该日暂无调用错误',
    APIVersionErrorCodeDistribution: 'API 版本错误分布',
    noErrorDataProduct: '该产品暂无调用错误',
    OpendAPIErrorCodeDistribution: 'OpenAPI 错误分布',
    noErrorDataVersion: '该版本暂无调用出错',
    noDebugData: '无调用信息',
    callAt: '调用日期：',
    currentAccount: '当前账号：',
    subAccount: '子账号',
    mainAccount: '主账号',
    cloundProduct: '云产品：',
    allVersion: '全部版本',
    noPublic: '不公开',
    recommend: '推荐',
    notRecommend: '不推荐',
    default: '，默认',
    versionTitle: '{val1}（{val2}）',
    allAPI: '全部 API',
    currentSelect: '当前选择：',
    totalCall: '总调用量',
    showNameCn: '{val1}（{val2}）',
    nodeHtml:
      "<div class='{val1}' xmlns=\"http://www.w3.org/1999/xhtml\"><p class='sign-text {val2}'>{val3}<span class='sign-value'>（{val4}）</span></p></div>",
    noCallDataDate: '该日无调用数据',
    callOverview: '调用次数概览',
    seeContent: '查看详情',
    nodeShowName: '{val1}（{val2}）',
    treeNodeHtml:
      "<div class='{val1}' xmlns=\"http://www.w3.org/1999/xhtml\"><p class='sign-text {val2}'>{val3}<span class='sign-value'>（{val4}）</span></p></div>",
    allCallNumber: '总调用次数',
    clientErrorCount: '4xx错误次数',
    clientError: '客户端引起的报错次数',
    serviceErrorCount: '5xx错误次数',
    serviceError: '服务端引起的报错次数',
    throttlingCount: '限流次数',
    percentText: '{val1}：{val2}%',
    calledOverview: '调用概览',
    APICallTrend: 'API 调用趋势',
    APIErrorCodeDistribution: 'API 错误分布',
  },
  userCenter: {
    updateState: '更新状态',
    reply: '回复：',
    hasFeedbackContent: '您向开发者门户反馈了以下内容',
    waitProcess: '等待处理',
    hasProcessed: '已受理',
    underConfirmation: '问题确认中',
    hasConfirm: '问题已确认',
    notAliyunIssue: '非阿里云问题',
    issueFixing: '问题修复中',
    issueFixed: '问题已修复',
    feedbackClosed: '反馈关闭',
    InterimPlan: '提供临时方案',
    dara: '新版',
    oldVersion: '原版',
    myFeedback: '我的反馈',
    feedbackDetail: '反馈详情 - {val1}',
    feedbackContent: '反馈内容',
    yourFeedback: '您反馈的{val1}',
    yourFeedbackContent: '您反馈的内容',
    feedbackProgress: '反馈处理进度',
    feedbackTime: '反馈时间',
    feedbackStatus: '处理进度',
    estimatedRepairTime: '预计修复时间',
    undetermined: '待定',
    feedbackProcessFlow: '反馈处理流程',
    notSupportReply: '继续回复该反馈问题的功能暂不支持， 您可以添加钉钉值班群',
    continueFeedback: '，进一步了解或补充该反馈问题。',
    paramName: '参数路径',
    feedback: '反馈',
    demoName: '示例名称',
    submitFeedbackTime: '提交反馈时间',
    yunProduct: '云产品',
    all: '全部',
    product: '产品',
    status: '状态',
    unread: '未读',
    operation: '操作',
    noFeedback: '暂无反馈, 请调整筛选条件',
    noFeedback1: '暂无反馈',
    openAssistant: '开通助手',
    openedProduct: '已开通的产品',
    hereStart: '从这里开始，集成阿里云 OpenAPI ...',
    subscribeChange: '订阅变更',
    productSelect: '请选择产品',
    version: '版本',
    versionSelect: '请选择版本',
    notificationType: '通知类型',
    notificationTypeSelect: '请选择通知类型',
    contactInformation: '联系方式',
    contentInput: '请输入内容',
    contactInformationSelect: '请填写联系方式',
    getAddress: '如何获得Webhook地址',
    invalidWebhook: '非法的钉钉机器人回调地址',
  },
  services: {
    apiMissDemo: 'API缺少Demo',
    SDKMissDemo: 'SDK缺少Demo',
    SDKMissLang: 'SDK缺少语言',
    reqNoParams: '当前OpenAPI无需请求参数',
  },
  index: {
    homeTitle: '阿里云 OpenAPI 开发者门户',
  },
};
