export default {
  utils: {
    cannotFindApi: "[findInterface]:找不到接口 {val1}",
    cannotFindApi2: "[findInterface]:找不到接口 {val1}",
  },
  profileManager: {
    creatFileError: "创建文件夹时出错:",
  },
  explorer: {
    mySubs: "我的订阅",
    aliyunProduct: "阿里云产品",
    switchAKProfiles: "点击切换您的 AK 信息",
    currentProfiles: '{val1}` : "点击配置您的 AK 信息"}',
    current: "当前: ",
    configProfiles: "点击配置您的 AK 信息",
    other: "其他",
    struct: "数据结构",
    deleteNewMeta: "传入的新元数据中已删除",
    updateNewMeta: "传入的新元数据中已更新",
    createNewMeta: "传入的新元数据中已新增",
    sameNewMeta: "与传入的新元数据等同，但子元数据存在不同",
    allreadySub: "该产品及其版本号已订阅，您可以使用「mac: ctrl+cmd+l」，「win: ctrl+alt+l」来搜索该产品下的API。",
    subSuccess: "订阅成功",
    feedbackInfo: "您在使用插件期间是否遇到问题？欢迎吐槽或点赞，您的反馈对我们十分重要！",
    gotoFeedback: "去反馈",
    limit30: "30天内不再弹出",
    successToCancelSub: "取消订阅成功",
    newSKProfile: "新增 AK 凭证配置",
    configAKProfile: "配置 AK 凭证",
    isSub: "是否订阅{val1}?",
    comfireToCancelSub: "确定取消订阅?",
  },
  commands: {
    recommandVersion: "推荐版本：{val1}",
    chooseAPIVersion: "选择 API 版本: {val1}",
    recmmandVersion2: "推荐版本",
    insertCode: "插入代码段: ",
    pullRemoteMeta: "拉取远程元数据",
    pullingMeta: "元数据拉取中...",
    pullMetaSuccess: "元数据拉取成功！",
    pullMetaFailed: "阿里云API元数据拉取失败：",
    restarting: "重启中...",
    startSuccess: "启动成功",
    startFailed: "启动失败: ",
    cannotFindOpenAPI: "未找到该 OpenAPI",
  },
  Service: {
    updateLocalMeta: "本地数据源更新中",
    listenConfigUpdate: "检测到 alicloud-api-toolkit-config.json 内容变化，Alibaba Cloud API Toolkit 重启中...",
    listenConfigCreate: "检测到 alicloud-api-toolkit-config.json 创建，Alibaba Cloud API Toolkit 重启中...",
    restart2: "Alibaba Cloud API Toolkit 重启中",
    startSuccess: "Alibaba Cloud API Toolkit 启动成功",
    AKSKTip: "请完成AK/SK配置后，再发起调用",
    gotoConfig: "去配置",
    cancel: "取消",
  },
};
