name: Smoke Test

on: [push]

jobs:
  smoke-test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"

      - name: Install yarn
        run: npm install --global yarn

      - name: Install Dependencies
        run: yarn

      - name: Run Smoke Test
        run: yarn -v
